image:
  file: .gitpod.Dockerfile

tasks:
  - name: Compile gearlock
    init: bashbox build --release
vscode:
  extensions:
    - timonwong.shellcheck
    - mads-hartmann.bash-ide-vscode
    - evgeniypeshkov.syntax-highlighter
    - ms-vscode.makefile-tools
